language: node_js
node_js:
- '0.10'
- '0.12'
- '4.0'
- '4.1'
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: QJ/BEh+p1OqveLRu0bJdC5naLlbzHc+U/zAW6zOUBzngzxDlO+B75AXAIRzOqZW3oDaW/dYI83ebOtSBAejyK4NZ3Tb1UDCAImlaXXS4cyKbklvX8bcf5sSYir9JHDn5MRy5aTU7178pDqf8ojkbYddHnDzG0yrmazyV2a9+fEY=
  on:
    tags: true
    repo: jakobmattsson/ftp-replace
notifications:
  email:
    on_success: never
    on_failure: always
