language: node_js
node_js:
- '0.10'
- '0.12'
- '4.0'
- '4.1'
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: XYWkWt2IAFT4qcZpb+UThY4LZiUzqXUC58vUq0CZ6/fVt0Bd6G7J4sMdDFmCEvxEiPDiWWvCBI2NvIdywIA3pnpA1UWpkbNbm4Vz4/8DU3Q5zc6MD6wA1lqGDEyYAKt999jizMSRd7UBGkHJvetph/JTgo+aSk6BXR9nAmUwnx4=
  on:
    branch: master
    repo: jakobmattsson/ftp-replace
notifications:
  email:
    on_success: never
    on_failure: always
